version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 4eburashka
      MYSQL_DATABASE: test
    networks:
      - my-network
    ports:
      - "3306:3306"
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:

