version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: sql/Dockerfile
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: Top
      MYSQL_PASSWORD: !234Qwer
      MYSQL_ROOT_PASSWORD: 1234!Qwerttyy

